# fly.toml - Configuration for Fly.io deployment

app = "kotoriminami"   # 🔹 Replace with your Fly.io app name

primary_region = "sin" # 🔹 Region close to you

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main.py"  # Starts your bot

[experimental]
  auto_rollback = true
